### ISSUE TITLE
[Bug]: your app is out of date. to run your app on ios 14, update to the latest facebook sdk for ios flutter

### ISSUE THREAD

**Issue by Bamschool** [oddbit/flutter_facebook_app_events#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I’m getting this error: “Your app version is outdated. To run the app on iOS 14, please update to the latest version of the Facebook SDK for iOS.”

However, I've already installed the SDK. When I go to Settings -> Advanced, it shows version 17.4. I don’t understand why it’s still telling me to update the SDK. None of the radio buttons are even selected, and I’ve already updated and released the SDK.

The SDK installation should be marked as completed since the latest SDK is installed to enable SKAdNetwork functionality.

![다운로드223](https://github.com/user-attachments/assets/55acc303-9482-4c34-bf8f-3018513e3802)

![Uploading 다운로드223.png…]()

<img width="1172" alt="스크린샷 2024-11-04 오후 8 46 11" src="https://github.com/user-attachments/assets/5a2ccce2-826c-4397-9387-b08490a913e1">

<img width="254" alt="스크린샷 2024-11-04 오후 8 19 29" src="https://github.com/user-attachments/assets/af150e40-a356-44fd-ac69-197bcb8d8765">

### Expected Behavior

The SDK installation should be marked as completed because I need to use SKAdNetwork, and it should indicate that the latest SDK is installed.

### Steps To Reproduce

Install the Latest Facebook SDK: Update to the latest version of the Facebook SDK for iOS, ensuring that SKAdNetwork support is enabled.
Configure Info.plist: Add the necessary SDK configurations accurately in the Info.plist, including settings to enable event reception.
Release the Updated SDK: Complete the release process with the updated SDK.
Open the App on an iOS 14 Device: Run the app on an iOS 14 device to confirm compatibility.
Check for Error Message: Observe the error message: “Your app version is outdated. To run the app on iOS 14, please update to the latest version of the Facebook SDK for iOS.”
Verify SDK Version in Facebook Settings:
Go to Settings -> Advanced in the Facebook developer console.
Confirm that the SDK version displayed is 17.4, as previously installed.
Note that none of the radio buttons in the settings are selected.

### Platform

iOS

### Flutter Doctor

perfect

**Comment by Bamschool** [comment]
Since Facebook App Events already includes the latest version of the SDK, does that mean I don’t need to install it separately in the Podfile?

**Comment by antonoddbit** [comment]
Hi @Bamschool I see you are using facebook_app_events (0.0.1), but the latest version is 0.19.3.
That issue is fixed on latest version.

**Comment by Bamschool** [comment]
Additional Information:
I removed social_share_plugin_ios due to concerns about potential conflicts with its Facebook SDK dependencies. The result remains the same. 

Note:
- Haven't released to App Store yet
- Tested on physical device
- facebook_app_events still shows as version 0.0.1 in Podfile.lock

Current Status:
- Removed potential conflict source (social_share_plugin_ios)
- Issue persists with facebook_app_events showing 0.0.1 in Podfile.lock
- Testing performed on actual device rather than simulator

**Comment by antonoddbit** [comment]
@Bamschool last time we got this issue is last year Sept.
Please kindly check #320  and #311 

Testing on actual device should showing in console minimum in 24 hours

**Comment by Bamschool** [comment]
@antonoddbit 
We already tested on actual device 3 days ago. I have a question. You pointed out that the version in the Podfile.lock is 0.0.1, but it actually says 0.19.3 in the pubspec.yaml. So, is it a big problem that it shows 0.0.1 in the Podfile.lock?

**Comment by Bamschool** [comment]
@antonoddbit 
Thank you for answering.

If that's the case, there's nothing I need to set in Info.plist if I download the actual Facebook app events package, even if I don't download native packages separately in the Podfile, right?

**Comment by fevzican** [comment]
Hello, I have the same problem. I see 17.4 as the SDK version on the App settings page, but in the “Data Sources” section it says “Update the Facebook SDK for iOS”. That's why I can't open iOS 14.5+ campaign.

**Comment by Bamschool** [comment]
It's working now. Actually I just have waited for a week. and it worked.
